# Generated by Django 3.1.7 on 2021-03-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='text',
            field=models.TextField(max_length=40000),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='research',
            name='text',
            field=models.TextField(max_length=40000),
        ),
    ]
