# Generated by Django 3.1.7 on 2021-03-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210327_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='short_description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
