# Generated by Django 3.1.7 on 2021-03-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210328_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleinstance',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
