# Generated by Django 3.1.7 on 2021-03-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_moduleinstance_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_success', models.CharField(choices=[('NA', 'Not applicable.'), ('GG', 'I think I did very well.'), ('QG', 'I think I mostly succeeded.'), ('QB', 'I think I was mostly unsuccessful.'), ('BB', 'I think I was completely unsuccessful.')], default='NA', max_length=2)),
                ('research_review', models.CharField(choices=[('NA', 'Not applicable.'), ('GG', 'It was fine.'), ('TL', 'It took too much time.'), ('TS', 'There was too little content.'), ('TD', "I didn't understand it.")], default='NA', max_length=2)),
                ('assignment_review', models.CharField(choices=[('NA', 'Not applicable.'), ('GG', 'It was fine.'), ('TL', 'It took too much time.'), ('TS', 'There was too little content.'), ('TD', "I didn't understand it.")], default='NA', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='review',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modulereview'),
        ),
    ]
