# Generated by Django 3.1.7 on 2021-03-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210329_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleinstance',
            name='review',
        ),
        migrations.AddField(
            model_name='modulereview',
            name='module_instance',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.moduleinstance'),
        ),
    ]
