# Generated by Django 3.1.7 on 2021-04-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleinstance',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='course_instances',
            field=models.ManyToManyField(to='app.CourseInstance'),
        ),
    ]
